### ISSUE TITLE
🗄️ OBJ Files

### ISSUE THREAD

**Issue by Quentintnrl** [epitech-mirroring/RTX#19]
# 👮‍♂️ What's needed
Handle OBJ file format

## 📋 Subtasks
- [ ] OBJ File loader

# 📜 Sources
You can check out this Wikipedia article: https://en.wikipedia.org/wiki/Wavefront_.obj_file

**Comment by RenardFute** [comment]
We should create an abstract class that represents loaders and then make the obj loader as a dynamic library
